export const UNIVERSAL_REGISTRY_ABI = [
  "function admin() view returns (address)",
  "function upsertIssuer(string did, string metadataURI, uint8 status)",
  "function setIssuerStatus(string did, uint8 status)",
  "function registerIssuer(string did, string metadataURI)",
  "function revokeIssuer(string did)",
  "function getIssuer(string did) view returns (uint8 status, string metadataURI, uint256 updatedAt)",
  "function upsertVerifier(string did, string metadataURI, uint8 status)",
  "function setVerifierStatus(string did, uint8 status)",
  "function registerVerifier(string did, string metadataURI)",
  "function revokeVerifier(string did)",
  "function getVerifier(string did) view returns (uint8 status, string metadataURI, uint256 updatedAt)",
  "function upsertSchema(bytes32 schemaId, string uri, uint8 status)",
  "function setSchemaStatus(bytes32 schemaId, uint8 status)",
  "function registerSchema(bytes32 schemaId, string uri)",
  "function revokeSchema(bytes32 schemaId)",
  "function getSchema(bytes32 schemaId) view returns (string uri, uint8 status, uint256 updatedAt)",
  "function upsertTemplate(bytes32 templateId, string uri, uint8 status)",
  "function setTemplateStatus(bytes32 templateId, uint8 status)",
  "function registerTemplate(bytes32 templateId, string uri)",
  "function revokeTemplate(bytes32 templateId)",
  "function getTemplate(bytes32 templateId) view returns (string uri, uint8 status, uint256 updatedAt)",
  "function upsertTrustRecord(bytes32 recordId, string registryId, string entityType, string entityId, string did, string metadataURI, uint8 status)",
  "function setTrustRecordStatus(bytes32 recordId, uint8 status)",
  "function getTrustRecord(bytes32 recordId) view returns (string registryId, string entityType, string entityId, string did, string metadataURI, uint8 status, uint256 updatedAt)",
  "function upsertGovernanceProposal(bytes32 proposalId, string issuerDid, string governanceType, string subjectType, string subjectId, uint256 requiredApprovals, uint8 status, string policyRef, string metadataURI)",
  "function approveGovernanceProposal(bytes32 proposalId)",
  "function getGovernanceProposal(bytes32 proposalId) view returns (string issuerDid, string governanceType, string subjectType, string subjectId, uint256 requiredApprovals, uint256 approvalCount, uint8 status, string policyRef, string metadataURI, uint256 updatedAt)",
  "function upsertStatusRoot(bytes32 statusListId, string listUri, string rootHash)",
  "function getStatusRoot(bytes32 statusListId) view returns (string listUri, string rootHash, uint256 updatedAt)",
  "event IssuerUpserted(string did, string metadataURI, uint8 status)",
  "event IssuerStatusUpdated(string did, uint8 status)",
  "event IssuerRegistered(string did, string metadataURI)",
  "event IssuerRevoked(string did)",
  "event VerifierUpserted(string did, string metadataURI, uint8 status)",
  "event VerifierStatusUpdated(string did, uint8 status)",
  "event VerifierRegistered(string did, string metadataURI)",
  "event VerifierRevoked(string did)",
  "event SchemaUpserted(bytes32 schemaId, string uri, uint8 status)",
  "event SchemaStatusUpdated(bytes32 schemaId, uint8 status)",
  "event SchemaRegistered(bytes32 schemaId, string uri)",
  "event SchemaRevoked(bytes32 schemaId)",
  "event TemplateUpserted(bytes32 templateId, string uri, uint8 status)",
  "event TemplateStatusUpdated(bytes32 templateId, uint8 status)",
  "event TemplateRegistered(bytes32 templateId, string uri)",
  "event TemplateRevoked(bytes32 templateId)",
  "event TrustRecordUpserted(bytes32 recordId, string registryId, string entityType, string entityId, uint8 status)",
  "event TrustRecordStatusUpdated(bytes32 recordId, uint8 status)",
  "event GovernanceProposalUpserted(bytes32 proposalId, string subjectType, string subjectId, uint8 status)",
  "event GovernanceProposalApproved(bytes32 proposalId, uint256 approvalCount, uint8 status)",
  "event StatusRootUpserted(bytes32 statusListId, string rootHash)",
] as const;
